namespace: default
namePrefix: nextcloud-

commonLabels:
  app: nextcloud
  version: "15"

bases:
  - redis
  - mariadb
  - nextcloud
  - cron

patchesStrategicMerge:
  - patch.yaml

vars:
  - name: DB_SERVICE
    objref:
      apiVersion: v1
      kind: Service
      name: db
  - name: REDIS_SERVICE
    objref:
      apiVersion: v1
      kind: Service
      name: redis